# Generated by Django 3.0.2 on 2020-02-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
