# Generated by Django 3.0.2 on 2020-02-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_auto_20200227_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='item',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='charge',
            name='type_name',
            field=models.CharField(max_length=20),
        ),
    ]
