# Generated by Django 3.0.2 on 2020-03-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0006_auto_20200227_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'type_category',
                'ordering': ['item_type'],
            },
        ),
        migrations.AlterModelOptions(
            name='charge',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelTable(
            name='charge',
            table='start_charge',
        ),
    ]
